### ISSUE TITLE
Display all players predictions for all past and ongoing matches

### ISSUE THREAD

**Issue by trouni** [trouni/predictor-vue#154]
Maybe on the Leaderboard#show page?

**Comment by dmbf29** [comment]
<img width="795" alt="Screen Shot 2022-11-22 at 14 39 17" src="https://user-images.githubusercontent.com/25542223/203233613-b260b67c-4534-426d-a1ed-c671bd1f81f4.png">
 
 kinda like this but have the user avatars underneath the prediction they chose

**Comment by jjmountain** [comment]
> <img alt="Screen Shot 2022-11-22 at 14 39 17" width="795" src="https://user-images.githubusercontent.com/25542223/203233613-b260b67c-4534-426d-a1ed-c671bd1f81f4.png">
> 
> kinda like this but have the user avatars underneath the prediction they chose

@dmbf29 I can't find this view. What is the route for it?

**Comment by jjmountain** [comment]
So I'm thinking for the results page (pictured below) we display a list of the past matches and when you click on a match card you see the results in your league like @dmbf29 suggested above. Is this what you guys were thinking?

<img width="150 alt="2022-11-26_16-38-19" src="https://user-images.githubusercontent.com/21108437/204077890-d289c7bd-d353-4622-8e18-508dbf0cdaa7.png">

The question is what should you display when the user is not in any league. I guess it would make most sense to just show your avatar in your predicted category, like this.

<img width="200" alt="player_predictions" src="https://user-images.githubusercontent.com/21108437/204078046-7c339128-cbc2-455d-9059-3aba5a4b3564.png">

**Comment by trouni** [comment]
Sorry, didn't see that comment @jjmountain 
For now, I'd say we only focus on users that are in a league. The idea is to use the same layout as the Rankings tab, but display matches with the predictions instead of the rankings.

**Comment by trouni** [comment]
It's already setup in this view:
https://github.com/trouni/predictor-vue/blob/leaderboard-results/src/views/Results.vue

Basically, what is left is to implement [this component](https://github.com/trouni/predictor-vue/blob/leaderboard-results/src/components/LeaderboardResultsCard.vue).

**Comment by trouni** [comment]
I don't have time to work on the design, but if it helps, I could probably quickly push out a first pass of the component to get the data on that page for you to design.

**Comment by jjmountain** [comment]
I started building it in `Results.vue` and with `LeaderboardResultsCard.vue` but I thought it made more sense for it to be based more like the matches (now called "predict") tab because you are displaying matches and the users choices within them. 

So far what I've built is this. 

<img width="444" alt="2022-11-28_20-51-30" src="https://user-images.githubusercontent.com/21108437/204271650-c4d07ee0-c5c0-4b9a-b4c6-330f3396e133.png">

I was planning to make the matches clickable so that when you do so you see the game at the top and each users predictions like in the sketch above. 

I don't mind changing it at all (actually having fun messing around with vue for the first time) but I'm confused about how it could be more like the leaderboard. 

Would it be just an index pages showing every past match with the people who predicted each score like the above sketch? To me it seems more like the matches/predict page except just with past matches, the results, and without the ability to predict.

**Comment by jjmountain** [comment]
I see now that the original feature was for **ongoing** match only. Oops 😅
I'll stash this for later and get to work on the original feature.

**Comment by trouni** [comment]
Yeah sorry it was definitely confusing... We were talking about it in person with Doug and kind of posted on the Slack thread with obviously some missing context... Anyway, let me push a quick implementation of the data that I've done. I think you can combine it with the percentage component that you started as well!
